### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Flimm** [mvolkmann/vim-js-arrow-function#2]
Please add a license to your code. If you don't add a license to your code, the code is copyrighted by default, which might not be what you intend. In the case that you do intend to disallow people from distributing your code, it would be good to explicitly state this in a license file.

Here's a useful resource on why this is a good idea, and instructions that will only take a couple of minutes:

https://help.github.com/articles/open-source-licensing/

Thanks!

**Comment by mvolkmann** [comment]
Done. I selected the MIT license. Thanks so much for improving the README and telling me about the license issue!
