### ISSUE TITLE
Toggle between single expression and multiple statements

### ISSUE THREAD

**Issue by OliverJAsh** [mvolkmann/vim-js-arrow-function#5]
I often need to toggle between the two formats of an arrow function. Single expression, e.g.:

``` js
x => x
```

And multiple statements

``` js
x => { console.log(x); return x; }
```

It would be great if there was a way to toggle between these two. E.g. from

``` js
x => x
```

to

``` js
x => { return x; }
```

and vice versa. Of course this would only be permitted if the multiple statement arrow function contained only one statement.

**Comment by mvolkmann** [comment]
Good suggestion! I'll think about whether I can support that.

---

R. Mark Volkmann
Object Computing, Inc.

**Comment by mvolkmann** [comment]
Done and done! Thanks for the suggestion!
Let me know if it doesn't work for you.
