### ISSUE TITLE
Merge this into coc-tsserver 

### ISSUE THREAD

**Issue by zeekhuge** [mvolkmann/vim-js-arrow-function#6]
Are there any plans to merge this into coc-tsserver ? Once merged, it should then be visible in the code-actions and would make working with this a breeze.

**Comment by mvolkmann** [comment]
I’m not familiar with coc-tsserver. Feel free to do whatever you’d like with this code. I don’t use Vim directly as much as used to. I spend most of my time now in VS Code using the Vim extension.

**Comment by zeekhuge** [comment]
Got it. Thanks.
